# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boundingBoxesMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainView(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 768))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bttn_selectimg = QtWidgets.QPushButton(self.frame_3)
        self.bttn_selectimg.setObjectName("bttn_selectimg")
        self.verticalLayout_3.addWidget(self.bttn_selectimg)
        self.lbl_rutai = QtWidgets.QLabel(self.frame_3)
        self.lbl_rutai.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_rutai.setObjectName("lbl_rutai")
        self.verticalLayout_3.addWidget(self.lbl_rutai)
        self.bttn_nopor = QtWidgets.QPushButton(self.frame)
        self.bttn_nopor.setObjectName("bttn_nopor")
        self.verticalLayout_3.addWidget(self.bttn_nopor)
        self.bttn_boxes = QtWidgets.QPushButton(self.frame_3)
        self.bttn_boxes.setObjectName("bttn_boxes")
        self.verticalLayout_3.addWidget(self.bttn_boxes)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bttn_prev = QtWidgets.QPushButton(self.frame_4)
        self.bttn_prev.setObjectName("bttn_prev")
        self.horizontalLayout_2.addWidget(self.bttn_prev)
        self.bttn_next = QtWidgets.QPushButton(self.frame_4)
        self.bttn_next.setObjectName("bttn_next")
        self.horizontalLayout_2.addWidget(self.bttn_next)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.listView = QtWidgets.QListWidget(self.frame)
        self.listView.setMaximumSize(QtCore.QSize(16777215, 250))
        self.listView.setObjectName("listView")
        self.verticalLayout_4.addWidget(self.listView)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_titulo = QtWidgets.QLabel(self.frame_2)
        self.lbl_titulo.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.verticalLayout.addWidget(self.lbl_titulo)
        self.lbl_imagen = QtWidgets.QLabel(self.frame_2)
        self.lbl_imagen.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_imagen.setObjectName("lbl_imagen")
        self.verticalLayout.addWidget(self.lbl_imagen)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.bttn_nopor.setStyleSheet(
            "background-color: red; color: white; border-radius: 2px;")
        self.bttn_boxes.setStyleSheet(
            "background-color: yellow; border-radius: 2px;")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BoundingBoxes"))
        self.bttn_selectimg.setText(_translate("MainWindow", "Abrir imagenes"))
        self.lbl_rutai.setText(_translate(
            "MainWindow", "Oprime el boton de\narriba para encontrar\ntus imagenes"))
        self.bttn_nopor.setText(_translate("MainWindow", "Inapropiada"))
        self.bttn_boxes.setText(_translate("MainWindow", "Sin objetos"))
        self.bttn_prev.setText(_translate("MainWindow", "prev"))
        self.bttn_next.setText(_translate("MainWindow", "next"))
        self.lbl_titulo.setText(_translate(
            "MainWindow", "Nombre de la imagen"))
        self.lbl_imagen.setText(_translate("MainWindow", "Imagen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainView()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
