# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowCourt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot, QObject


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 457)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_imagen = QtWidgets.QLabel(Form)
        self.lbl_imagen.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_imagen.setObjectName("lbl_imagen")
        self.verticalLayout.addWidget(self.lbl_imagen)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_bttn_a = QtWidgets.QRadioButton(self.frame)
        self.radio_bttn_a.setObjectName("radio_bttn_a")
        self.horizontalLayout.addWidget(self.radio_bttn_a)
        self.radio_bttn_b = QtWidgets.QRadioButton(self.frame)
        self.radio_bttn_b.setObjectName("radio_bttn_b")
        self.horizontalLayout.addWidget(self.radio_bttn_b)
        self.radio_bttn_c = QtWidgets.QRadioButton(self.frame)
        self.radio_bttn_c.setObjectName("radio_bttn_c")
        self.horizontalLayout.addWidget(self.radio_bttn_c)
        self.radio_bttn_d = QtWidgets.QRadioButton(self.frame)
        self.radio_bttn_d.setObjectName("radio_bttn_d")
        self.horizontalLayout.addWidget(self.radio_bttn_d)
        self.radio_bttn_e = QtWidgets.QRadioButton(self.frame)
        self.radio_bttn_e.setObjectName("radio_bttn_e")
        self.horizontalLayout.addWidget(self.radio_bttn_e)
        self.radio_bttn_f = QtWidgets.QRadioButton(self.frame)
        self.radio_bttn_f.setObjectName("radio_bttn_f")
        self.horizontalLayout.addWidget(self.radio_bttn_f)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_imagen.setText(_translate("Form", "Imagen Recortada"))
        self.radio_bttn_a.setText(_translate("Form", "surgical"))
        self.radio_bttn_b.setText(_translate("Form", "valve"))
        self.radio_bttn_c.setText(_translate("Form", "cloth"))
        self.radio_bttn_d.setText(_translate("Form", "respirator"))
        self.radio_bttn_e.setText(_translate("Form", "others"))
        self.radio_bttn_f.setText(_translate("Form", "none"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
