# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowCourt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form, pix):
        Form.setObjectName("Form")
        Form.resize(550, 457)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_imagen = QtWidgets.QLabel(Form)
        self.lbl_imagen.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_imagen.setObjectName("lbl_imagen")
        self.verticalLayout.addWidget(self.lbl_imagen)
        self.retranslateUi(Form)
        self.lbl_imagen.setPixmap(pix)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_imagen.setText(_translate("Form", "Imagen Recortada"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
